### ISSUE TITLE
Postinstall prevents installation as a dependency

### ISSUE THREAD

**Issue by srconne** [esm-bundle/react#147]
The package.json specifies a postinstall which initializes husky. Upon an npm install this postinstall step triggers husky which attempts to locate a '.git' folder within the node module. This step fails as it is not a git repo resulting in a failed module installation.
See: [typicode/husky#884](https://github.com/typicode/husky/issues/884)

**Comment by TheMcMurder** [comment]
This should be resolved in `17.0.2-fix.0` and `17.0.2-fix.1`
